// This file will be auto-generated by Supabase CLI after database setup
// For now, we'll use a simplified type definition

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          role: 'client' | 'coach' | 'admin';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          role?: 'client' | 'coach' | 'admin';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          role?: 'client' | 'coach' | 'admin';
          created_at?: string;
          updated_at?: string;
        };
      };
      coaches: {
        Row: {
          id: string;
          bio: string | null;
          specialties: string[];
          years_experience: number | null;
          is_approved: boolean;
          default_zoom_link: string | null;
          stripe_connect_account_id: string | null;
          stripe_onboarding_complete: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          bio?: string | null;
          specialties?: string[];
          years_experience?: number | null;
          is_approved?: boolean;
          default_zoom_link?: string | null;
          stripe_connect_account_id?: string | null;
          stripe_onboarding_complete?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          bio?: string | null;
          specialties?: string[];
          years_experience?: number | null;
          is_approved?: boolean;
          default_zoom_link?: string | null;
          stripe_connect_account_id?: string | null;
          stripe_onboarding_complete?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
};
